Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SurRon.Infrastructure.Data;
using SurRon.Infrastructure.Data.Models;
using SurRon.Core.Models.Events;
using System.Security.Claims;
using static SurRon.Infrastructure.DataConstants.EventConstants;

namespace SurRon.Controllers
{
    public class EventController : BaseController
    {
        private readonly SurRonDbContext _data;

        public EventController(SurRonDbContext context)
        {
            _data = context;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var events = await _data.Events
                .AsNoTracking()
                .Select(e => new EventViewModel(
                    e.Id,
                    e.Name,
                    e.Description,
                    e.Date,
                    e.Location,
                    e.Organizer.UserName
                ))
                .ToListAsync();

            return View(events);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var model = new EventFormViewModel
            {
                Date = DateTime.Now
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(EventFormViewModel model)
        {
            var entity = new Event()
            {
                Name = model.Name,
                Location = model.Location,
                Description = model.Description,
                OrganizerId = GetUserId(),
                Date = model.Date
            };

            await _data.Events.AddAsync(entity);
            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var e = await _data.Events
                .FindAsync(id);

            if (e == null)
            {
                return BadRequest();
            }

            if (e.OrganizerId != GetUserId())
            {
                return Unauthorized();
            }

            var model = new EventFormViewModel()
            {
                Name = e.Name,
                Location = e.Location,
                Description = e.Description,
                Date = e.Date
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EventFormViewModel model, int id)
        {
            var e = await _data.Events
                .FindAsync(id);

            if (e == null)
            {
                return BadRequest();
            }

            if (e.OrganizerId != GetUserId())
            {
                return Unauthorized();
            }

            e.Name = model.Name;
            e.Location = model.Location;
            e.Description = model.Description;
            e.Date = model.Date;
            e.OrganizerId = GetUserId();

            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> Join(int id)
        {
            var e = await _data.Events
                .Where(e => e.Id == id)
                .Include(e => e.EventsParticipants)
                .FirstOrDefaultAsync();

            if (e == null)
            {
                return BadRequest();
            }

            string userId = GetUserId();

            var entry = new EventParticipant()
            {
                EventId = e.Id,
                ParticipantId = userId
            };

            if (await _data.EventsParticipants.ContainsAsync(entry))
            {
                return RedirectToAction(nameof(All));
            }

            await _data.EventsParticipants.AddAsync(entry);
            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(Joined));

        }

        [HttpGet]
        public async Task<IActionResult> Joined()
        {
            string userId = GetUserId();

            var model = await _data.EventsParticipants
                .Where(sp => sp.ParticipantId == userId)
                .AsNoTracking()
                .Select(sp => new EventViewModel(
                    sp.EventId,
                    sp.Event.Name,
                    sp.Event.Description,
                    sp.Event.Date,
                    sp.Event.Location,
                    sp.Event.Organizer.UserName
                ))
                .ToListAsync();


            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Leave(int id)
        {
            var e = await _data.Events
                .Where(e => e.Id == id)
                .Include(e => e.EventsParticipants)
                .FirstOrDefaultAsync();

            if (e == null)
            {
                return BadRequest();
            }

            string userId = GetUserId();

            var ep = e.EventsParticipants
                .FirstOrDefault(ep => ep.ParticipantId == userId);

            if (ep == null)
            {
                return BadRequest();
            }

            e.EventsParticipants.Remove(ep);
            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(Joined));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var model = await _data.Events
                .Where(e => e.Id == id)
                .AsNoTracking()
                .Select(e => new EventDetailsModel()
                {
                    Id = e.Id,
                    Name = e.Name,
                    Date = e.Date,
                    Description = e.Description,
                    Location = e.Location,
                    Organizer = e.Organizer.UserName
                })
                .FirstOrDefaultAsync();

            if (model == null)
            {
                return BadRequest();
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var e = await _data.Events
                .FindAsync(id);

            if (e == null)
            {
                return BadRequest();
            }

            if (e.OrganizerId != GetUserId())
            {
                return Unauthorized();
            }

            var model = await _data.Events
                .Where(e => e.Id == id)
                .AsNoTracking()
                .Select(e => new EventDeleteModel()
                {
                    Id = e.Id,
                    Name = e.Name,
                    Date = e.Date,
                    Organizer = e.Organizer.UserName
                })
                .FirstOrDefaultAsync();

            if (model == null)
            {
                return BadRequest();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var e = await _data.Events
                .Where(s => s.Id == id)
                .Include(e => e.EventsParticipants)
                .FirstOrDefaultAsync();

            if (e == null)
            {
                return BadRequest();
            }

            if (e.OrganizerId != GetUserId())
            {
                return Unauthorized();
            }

            var ep = e.EventsParticipants
                .FirstOrDefault(ep => ep.EventId == e.Id);

            if (ep != null)
            {
                _data.EventsParticipants.Remove(ep);
            }

            _data.Events.Remove(e);
            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        private string GetUserId()
        {
            return User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
        }
    }
}

Controllers/InventoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SurRon.Core.Models.Inventory;
using SurRon.Infrastructure.Data;
using SurRon.Infrastructure.Data.Models;

namespace SurRon.Controllers
{
    public class InventoryController : BaseController
    {

        private readonly SurRonDbContext _data;

        public InventoryController(SurRonDbContext context)
        {
            _data = context;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var items = await _data.Inventory
                .AsNoTracking()
                .Select(i => new InventoryViewModel(
                    i.Id,
                    i.Name,
                    i.Price,
                    i.Amount,
                    i.ImageUrl
                ))
                .ToListAsync();

            return View(items);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var model = new InventoryFormViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(InventoryFormViewModel model)
        {
            var entity = new Inventory()
            {
                Name = model.Name,
                Price = model.Price,
                Amount = model.Amount,
                ImageUrl = model.ImageUrl
            };

            await _data.Inventory.AddAsync(entity);
            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Search(string searchString)
        {
            var items = await _data.Inventory
                .Where(i => i.Name == searchString)
                .AsNoTracking()
                .Select(i => new InventoryViewModel(
                    i.Id,
                    i.Name,
                    i.Price,
                    i.Amount,
                    i.ImageUrl
                ))
                .ToListAsync();

            if (items.Count == 0)
            {
                return RedirectToAction(nameof(All));
            }

            return View(items);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var e = await _data.Inventory
                .FindAsync(id);

            if (e == null)
            {
                return BadRequest();
            }

            var model = new InventoryFormViewModel()
            {
                Name = e.Name,
                Amount = e.Amount,
                Price = e.Price,
                ImageUrl = e.ImageUrl
            };
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(InventoryFormViewModel model, int id)
        {
            var e = await _data.Inventory
                .FindAsync(id);

            if (e == null)
            {
                return BadRequest();
            }

            e.Name = model.Name;
            e.Price = model.Price;
            e.Amount = model.Amount;
            e.ImageUrl = model.ImageUrl;

            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var e = await _data.Inventory
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();

            if (e == null)
            {
                return BadRequest();
            }

            _data.Inventory.Remove(e);

            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }
    }
}

Controllers/SoldMotorcyclesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SurRon.Controllers;
using SurRon.Core.Models.Inventory;
using SurRon.Core.Models.MotorcycleTypes;
using SurRon.Core.Models.SoldMotorcycles;
using SurRon.Infrastructure.Data;
using SurRon.Infrastructure.Data.Models;
using System.Security.Claims;

namespace SurRon.Controllers
{
    public class SoldMotorcyclesController : BaseController
    {
        private readonly SurRonDbContext _data;

        public SoldMotorcyclesController(SurRonDbContext context)
        {
            _data = context;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var motors = await _data.SoldMotorcycles
                .AsNoTracking()
                .Select(m => new SoldMotorcyclesViewModel(
                    m.Id,
                    m.Name,
                    m.Address,
                    m.City,
                    m.Country,
                    m.DateSold,
                    m.Vin,
                    m.Color,
                    m.Engine,
                    m.MotorcycleType.Name,
                    m.Uploader.UserName,
                    m.Warranty
                ))
                .ToListAsync();

            return View(motors);
        }

        [HttpGet]
        public async Task<IActionResult> Search(string searchString)
        {
            var motors = await _data.SoldMotorcycles
                .Where(m => m.Vin == searchString)
                .AsNoTracking()
                .Select(m => new SoldMotorcyclesViewModel(
                    m.Id,
                    m.Name,
                    m.Address,
                    m.City,
                    m.Country,
                    m.DateSold,
                    m.Vin,
                    m.Color,
                    m.Engine,
                    m.MotorcycleType.Name,
                    m.Uploader.UserName,
                    m.Warranty
                ))
                .ToListAsync();

            if (motors.Count == 0)
            {
                return RedirectToAction(nameof(All));
            }

            return View(motors);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new SoldMotorcycleFormViewModel
            {
                DateSold = DateTime.Today,
                MotorcycleType = await GetMotorcycleTypes()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(SoldMotorcycleFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.MotorcycleType = await GetMotorcycleTypes();
            }

            var entity = new SoldMotorcycles()
            {
                Name = model.Name,
                Address = model.Address,
                City = model.City,
                Country = model.Country,
                DateSold = model.DateSold,
                Vin = model.Vin,
                Color = model.Color,
                Engine = model.Engine,
                MotorcycleTypeId = model.MotorcycleTypeId,
                UploaderId = GetUserId()
            };

            if (_data.SoldMotorcycles.Contains(entity))
            {
                return BadRequest();
            }

            await _data.SoldMotorcycles.AddAsync(entity);
            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> SellItem()
        {
            var model = new SellItemFormViewModel
            {
                SoldOn = DateTime.Today,
                InventoryItems = await GetItemTypes()
            };

            return View(model);
        }

        private string GetUserId()
        {
            return User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
        }

        private async Task<IEnumerable<MotorcycleTypeView>> GetMotorcycleTypes()
        {
            return await _data.MotorcycleTypes
                .AsNoTracking()
                .Select(m => new MotorcycleTypeView()
                {
                    Id = m.Id,
                    Name = m.Name
                })
                .ToListAsync();
        }

        private async Task<IEnumerable<InventoryTypeView>> GetItemTypes()
        {
            return await _data.Inventory
                .AsNoTracking()
                .Select(i => new InventoryTypeView()
                {
                    Id = i.Id,
                    Name = i.Name
                })
                .ToListAsync();
        }
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SurRon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SurRon.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" id="navbar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SurRon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Events
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-action="All" asp-controller="Event">All</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-action="Add" asp-controller="Event">Add</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-action="Joined" asp-controller="Event">Joined</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="False">
                                    Motorcycles
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-action="All" asp-controller="Motorcycle">All</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-action="Add" asp-controller="Motorcycle">Add</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="False">
                                    Sold Motorcycles
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-action="All" asp-controller="SoldMotorcycles">All</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-action="Add" asp-controller="SoldMotorcycles">Add</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="False">
                                    Inventory
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-action="All" asp-controller="Inventory">All</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-action="Add" asp-controller="Inventory">Add</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - @DateTime.Now.Year - SurRon - Powered by DragonCorps
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Areas/Admin/Views/Shared/_NavItemsAfterLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Events
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" asp-area="" asp-action="All" asp-controller="Event">All</a></li>
                <li><a class="dropdown-item" href="#">Add</a></li>
            </ul>
        </li>
    }
    else
    {
        <script>window.location.href = '@Url.Content("~/")';</script>
    }
</ul>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>