Controllers/MotorcycleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SurRon.Core.Models.Motorcycles;
using SurRon.Core.Models.MotorcycleTypes;
using SurRon.Infrastructure.Data;
using SurRon.Infrastructure.Data.Models;
using System.Security.Claims;

namespace SurRon.Controllers
{
    public class MotorcycleController : BaseController
    {
        private readonly SurRonDbContext _data;

        public MotorcycleController(SurRonDbContext context)
        {
            _data = context;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var motors = await _data.Motorcycles
                .AsNoTracking()
                .Select(m => new MotorcycleViewModel(
                    m.Id,
                    m.Vin,
                    m.Color,
                    m.Engine,
                    m.MotorcycleType.Name,
                    m.Uploader.UserName
                ))
                .ToListAsync();

            return View(motors);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new MotorcycleFormViewModel
            {
                MotorcycleType = await GetMotorcycleTypes()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(MotorcycleFormViewModel model)
        {

            if (!ModelState.IsValid)
            {
                model.MotorcycleType = await GetMotorcycleTypes();
            }

            var entity = new Motorcycle()
            {
                Vin = model.Vin,
                Color = model.Color,
                Engine = model.Engine,
                UploaderId = GetUserId(),
                MotorcycleTypeId = model.MotorcycleTypeId
            };

            if (_data.Motorcycles.Contains(entity))
            {
                return BadRequest();
            }

            await _data.Motorcycles.AddAsync(entity);
            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var e = await _data.Motorcycles
                .FindAsync(id);

            if (e == null)
            {
                return BadRequest();
            }

            var model = await _data.Motorcycles
                .Where(x => x.Id == id)
                .Select(m => new MotorcycleFormViewModel()
                {
                    Vin = m.Vin,
                    Color = m.Color,
                    Engine = m.Engine,
                    MotorcycleTypeId = m.MotorcycleTypeId
                })
                .FirstOrDefaultAsync();

            if (model == null)
            {
                return BadRequest();
            }

            model.MotorcycleType = await GetMotorcycleTypes();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MotorcycleFormViewModel model, int id)
        {
            var e = await _data.Motorcycles
                .FindAsync(id);

            if (e == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                model.MotorcycleType = await GetMotorcycleTypes();
            }

            e.Vin = model.Vin;
            e.Color = model.Color;
            e.Engine = model.Engine;
            e.MotorcycleTypeId = model.MotorcycleTypeId;

            await _data.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Search(string searchString)
        {
            var motors = await _data.Motorcycles
                .Where(m => m.Vin == searchString)
                .AsNoTracking()
                .Select(m => new MotorcycleViewModel(
                    m.Id,
                    m.Vin,
                    m.Color,
                    m.Engine,
                    m.MotorcycleType.Name,
                    m.Uploader.UserName
                ))
                .ToListAsync();

            if (motors.Count == 0)
            {
                return RedirectToAction(nameof(All));
            }

            return View(motors);
        }

        [HttpGet]
        public async Task<IActionResult> Sell(int id)
        {
            var m = await _data.Motorcycles
                .FindAsync(id);

            if (m == null)
            {
                return BadRequest();
            }

            var model = await _data.Motorcycles
                .Where(x => x.Id == id)
                .Select(m => new MotorcycleSellViewModel()
                {
                    Id = id,
                    Name = "",
                    DateTime = DateTime.Today,
                    Address = "",
                    City = "",
                    Country = "",
                    Vin = m.Vin,
                    Engine = m.Engine,
                    Color = m.Color,
                    MotorcycleType = m.MotorcycleType.Name
                })
                .FirstOrDefaultAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Sell(MotorcycleSellViewModel model, int id)
        {
            var m = await _data.Motorcycles
                .Where(x => x.Id == id)
                .Include(x => x.SellerMotorcycles)
                .FirstOrDefaultAsync();

            if (m == null)
            {
                return BadRequest();
            }
            
            var soldModel = new SoldMotorcycles()
            {
                Name = model.Name,
                Vin = model.Vin,
                Engine = model.Engine,
                DateSold = model.DateTime,
                City = model.City,
                Address = model.Address,
                Country = model.Country,
                Color = model.Color,
                MotorcycleTypeId = m.MotorcycleTypeId,
                Warranty = true,
                UploaderId = GetUserId()
            };
            
            await _data.SoldMotorcycles.AddAsync(soldModel);
        
            _data.Motorcycles.Remove(m);
            await _data.SaveChangesAsync();

            return RedirectToAction("All", "SoldMotorcycles");
        }

        [AllowAnonymous]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {

            if (statusCode == 400)
            {
                return View("Error404");
            }

            if (statusCode == 401)
            {
                return View("Error500");
            }

            return View();
        }

        private string GetUserId()
        {
            return User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
        }

        private async Task<IEnumerable<MotorcycleTypeView>> GetMotorcycleTypes()
        {
            return await _data.MotorcycleTypes
                .AsNoTracking()
                .Select(m => new MotorcycleTypeView()
                {
                    Id = m.Id,
                    Name = m.Name
                })
                .ToListAsync();
        }
    }
}

Areas/Admin/Views/Motorcycle/Add.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers;
@model SurRon.Core.Models.Motorcycles.MotorcycleFormViewModel

@{
    ViewBag.Title = "Add Motorcycle";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Add" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Vin" class="form-label-add-edit">Vin</label>
                <input asp-for="@Model.Vin" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Vin" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Engine" class="form-label-add-edit">Engine</label>
                <input asp-for="@Model.Engine" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Engine" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Color" class="form-label-add-edit">Color</label>
                <input asp-for="@Model.Color" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Color" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.MotorcycleTypeId" class="form-label-add-edit">Select Motorcycle Type</label>
                <select asp-for="@Model.MotorcycleTypeId" class="form-control" aria-required="true">
                    <option disabled selected value="">Select Motorcycle Type...</option>
                    @foreach (var category in Model.MotorcycleType)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.MotorcycleTypeId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Announce" />
            </div>
        </form>
    </div>
</div>

<link href="@Url.Content("~/css/StyleForAllViews.css")" rel="stylesheet" type="text/css" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Areas/Admin/Views/Motorcycle/All.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<SurRon.Core.Models.Motorcycles.MotorcycleViewModel>
@using Microsoft.CodeAnalysis.Scripting

@{
    ViewBag.Title = "All Motorcycles";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<form asp-controller="Motorcycle" asp-action="Search" method="get">
    <p style="padding-bottom: 2rem; padding-top: 1rem; color: yellow">
        <input style="background: black; border-color: yellow; color: white" type="text" name="searchString" placeholder="Search by VIN" />
        <input style="background: yellow; font-weight: bold" type="submit" value="Search" />
    </p>
</form>

<div class="text-center row">
    @foreach (var m in Model)
    {
        <div class="card col-4" style="width: 20rem">
            <div class="card-body">
                <h5 class="card-title mt-1">@m.MotorcycleType</h5>
                <h6 class="card-title mt-1">@m.Engine</h6>
                <h6 class="card-title mt-1">@m.Color</h6>
                <h6 class="card-title mt-1">@m.Vin</h6>
            </div>
            <a asp-controller="Motorcycle" asp-action="Edit" asp-route-id="@m.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit</a>
            <a asp-controller="Motorcycle" asp-action="Sell" asp-route-id="@m.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Sell</a>
            <a asp-controller="Motorcycle" asp-action="Delete" asp-route-id="@m.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Delete</a>
        </div>


        
    }
</div>

<link href="@Url.Content("~/css/StyleForAllViews.css")" rel="stylesheet" type="text/css" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Areas/Admin/Views/Motorcycle/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers;
@model SurRon.Core.Models.Motorcycles.MotorcycleFormViewModel

@{
    ViewBag.Title = "Edit Motorcycle";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Edit" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Vin" class="form-label-add-edit">Vin</label>
                <input asp-for="@Model.Vin" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Vin" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Engine" class="form-label-add-edit">Engine</label>
                <input asp-for="@Model.Engine" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Engine" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Color" class="form-label-add-edit">Color</label>
                <input asp-for="@Model.Color" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Color" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.MotorcycleTypeId" class="form-label-add-edit">Select Motorcycle Type</label>
                <select asp-for="@Model.MotorcycleTypeId" class="form-control" aria-required="true">
                    <option disabled selected value="">Select Motorcycle Type...</option>
                    @foreach (var category in Model.MotorcycleType)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.MotorcycleTypeId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Announce" />
            </div>
        </form>
    </div>
</div>

<link href="@Url.Content("~/css/StyleForAllViews.css")" rel="stylesheet" type="text/css" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Areas/Admin/Views/Motorcycle/Error400.cshtml
@{
    ViewData["Title"] = "Error 404";
}

<body>
<picture>
    <sources src="~/Media/Pictures/Error404.webp" type="img"/>
</picture>
</body>

Areas/Admin/Views/Motorcycle/Error404.cshtml
@{
    ViewData["Title"] = "Error 400";
}

<body>
<img src="Media/Pictures/Error404.webp"/>
</body>

Areas/Admin/Views/Motorcycle/Error500.cshtml
@{
    ViewData["Title"] = "Error 500";
}

<img src="Media/Pictures/"/>

Areas/Admin/Views/Motorcycle/Search.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<SurRon.Core.Models.Motorcycles.MotorcycleViewModel>
@using Microsoft.CodeAnalysis.Scripting

@{
    ViewBag.Title = "All Motorcycles";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<form asp-controller="Motorcycle" asp-action="Search" method="get">
    <p style="padding-bottom: 2rem; padding-top: 1rem; color: yellow">
        <input style="background: black; border-color: yellow; color: white" type="text" name="searchString" placeholder="Search by VIN" />
        <input style="background: yellow; font-weight: bold" type="submit" value="Search" />
    </p>
</form>

<div class="text-center row">
    @foreach (var m in Model)
    {
        <div class="card col-4" style="width: 20rem">
            <div class="card-body">
                <h5 class="card-title mt-1">@m.MotorcycleType</h5>
                <h6 class="card-title mt-1">@m.Engine</h6>
                <h6 class="card-title mt-1">@m.Color</h6>
                <h6 class="card-title mt-1">@m.Vin</h6>
            </div>
            <a asp-controller="Motorcycle" asp-action="Edit" asp-route-id="@m.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit</a>
            <a asp-controller="Motorcycle" asp-action="Sell" asp-route-id="@m.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Sell</a>
            <a asp-controller="Motorcycle" asp-action="Delete" asp-route-id="@m.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Delete</a>
        </div>
    }
</div>

<link href="@Url.Content("~/css/StyleForAllViews.css")" rel="stylesheet" type="text/css" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Areas/Admin/Views/Motorcycle/Sell.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers;
@model SurRon.Core.Models.Motorcycles.MotorcycleSellViewModel

@{
    ViewBag.Title = "Sell Motorcycle";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Sell" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Name" class="form-label-add-edit">Name</label>
                <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.DateTime" class="control-label">Date</label>
                <input asp-for="@Model.DateTime" class="form-control" />
                <span asp-validation-for="@Model.DateTime" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Address" class="form-label-add-edit">Address</label>
                <input asp-for="@Model.Address" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Address" class="text-danger"></span>
            </div><div class="mb-3">
                <label asp-for="@Model.City" class="form-label-add-edit">City</label>
                <input asp-for="@Model.City" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.City" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Country" class="form-label-add-edit">Country</label>
                <input asp-for="@Model.Country" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Country" class="text-danger"></span>
            </div><div class="mb-3">
                <label asp-for="@Model.Vin" class="form-label-add-edit">Vin</label>
                <input asp-for="@Model.Vin" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Vin" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Engine" class="form-label-add-edit">Engine</label>
                <input asp-for="@Model.Engine" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Engine" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Color" class="form-label-add-edit">Color</label>
                <input asp-for="@Model.Color" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Color" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.MotorcycleType" class="form-label-add-edit">Motorcycle Type</label>
                <input asp-for="@Model.MotorcycleType" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.MotorcycleType" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <form class="input-group-sm" asp-controller="Motorcycle" asp-action="Sell" asp-route-id="@Model.Id">
                    <input type="submit" value="Subscribe" class="fs-6 btn btn-warning mb-2 w-100 p-3 fw-bold" />
                </form>
            </div>
        </form>
    </div>
</div>

<link href="@Url.Content("~/css/StyleForAllViews.css")" rel="stylesheet" type="text/css" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}